### ISSUE TITLE
question about lineage tree and interpretation Fig 5c

### ISSUE THREAD

**Issue by jessielyons** [vibscc/DALI#18]
Hi DALI team,

Can you please clarify, how do you build the lineage tree. So e.g. it seems like the clonotypes you are referring to are output from cell ranger and integrated with GEX.

The app calls for uploading a VDJ reference fasta which is by default provided as "regions.fa".  I am trying to understand biologically, what's the process and interpretation.

1) What is regions.fa file asked to be provided as an input? Does it have to be computed by us or is it available from cell ranger for human genome?

2) The example "regions.fa" file provided seems to be a nucleotide sequence. What does this sequence correspond to?

3) If above is a standard "regions.fa" file, what does your tree algorithm do? In your publication, you take all the clonotypes within "cluster 7" and run a tree algorithm? 

4) What is the tree algorithm above based on? Is it running multiple sequence alignment across all clonotypes within cluster 7 or something else? And what is the sequence being aligned? It appears once you have run msa then you color the tree with whatever needed.

5) If it's just MSA across clonotypes, how do you determine "root" of the tree?

Thanks so much again, Jessie

**Comment by kverstae** [comment]
1. The `regions.fa` file is basically the reference that Cellranger used to 'map' the VDJ data. You can either find it in the reference folder you used (`fasta` subdirectory), but is also included in the output of `cellranger vdj` (`outs/vdj_reference/fasta`). In a future update of DALI, we will include this file for mouse and human so it can be directly used without having to find it yourself (given that the data is mapped to the same reference)
2. As mentioned above, these are reference sequences for the V, D, J and C segments. The references provided by 10x are assembled from the IMGT-database. These can be seen as the germline sequences
3. The trees calculated are within 1 clonotype, not within 1 cluster. For the figure in the paper, we just calculated the tree based on the sequences of the V-region of the heavy chain. 
4. We currently just build a naive neighbor-joining tree from a distance matrix (levenshtein distance) of the requested sequences (default: V-region of heavy chain, but could also be any other regions or combination of regions). The sequences are gathered for all cells that have the requested clonotype + the 'ground truth'/germline sequence that we get from `regions.fa`. Once we have the tree, we can indeed just color the nodes by whatever we want.
5. The root of the tree is just the sequence we get from `region.fa`.

We are aware that the current approach to build this tree is not ideal and maybe a bit too naive to capture the complexity of BCR lineages. There are other tools (like the tools provided by Immcantation) that provide a more complex (and probably more accurate) way of building these trees. We are trying to find a way to incorporate one (or more) of these tools in DALI to make the trees more robust than our current implementation.
