### ISSUE TITLE
Installation error: Missing commas separating Remotes

### ISSUE THREAD

**Issue by yujuanGG** [vibscc/DALI#22]
Hi! I encountered the below installation error with the new built: 

> devtools::install_github("vibscc/DALI")
Downloading GitHub repo vibscc/DALI@HEAD
Error: Failed to install 'DALI' from GitHub:
    Missing commas separating Remotes: 'dynverse/dynplot
dynverse/dynwrap
YuLab-SMU/ggtree'

Could you kindly take a look?

**Comment by kverstae** [comment]
Hi,

Thanks for notifying us about the issue.
I have fixed this issue and installation should now work.

Kind regards,

Kevin
