### ISSUE TITLE
How to export high resolution images from DALI analysis results?

### ISSUE THREAD

**Issue by HaiqiaoSun** [vibscc/DALI#23]
Please tell me how to export high resolution images from the DALI interface. The copy image function produces images with insufficient resolution, and the width and height are usually very strange.

**Comment by kverstae** [comment]
All plots displayed in the DALI interface can be generated in R using the functions from DALI.
We are currently lacking documentation on how to do this. If you let me know which plot you would like in a higher resolution, I can create an example you can run in R.

**Comment by HaiqiaoSun** [comment]
> 

Would you like to tell me how to generate the _Hierarchical clustering plot_ and the _Family & Chain usage plot_ by using the functions in DALI? 
This would be an example of exporting high resolution plots using DALI. That would be a great help!

**Comment by kverstae** [comment]
This is an example for the Family & Chain usage plots:
```
library("Seurat")
library("DALI")

# Read the seurat rds file
seuratObj <- readRDS("/PATH/TO/SEURAT.rds")

# Add the VDJ data. If you have both TCR and BCR, you need to do this step once for each modality.
seuratObj <- Read10X_vdj(seuratObj, "/PATH/TO/CELLRANGER_BCR_OR_TCR_OUTPUT")

# If you have both BCR and TCR, you can specifiy which assay you currently want to use with following commands:
# DefaultAssayVDJ(seuratObj) <- "BCR"
# DefaultAssayVDJ(seuratObj) <- "TCR"

# Create a pdf from the plot. Change pdf with png or jpeg if you want an image instead of a pdf
# Plots will be stored in the working directory.
pdf("circosplot_chains.pdf")
  CircosPlotChains(seuratObj)
dev.off()

pdf("circosplot_genes.pdf")
  CircosPlotGenes(seuratObj)
dev.off()
```
I am not sure what plot you mean with the _Hierarchical clustering plot_ ...
To get an overview of all available functions in DALI, you can use the following command: `help(package = "DALI")`

Hopefully this will help you get started. If you have more questions, feel free to let me know
