### ISSUE TITLE
How to plot the tree shown in your publication

### ISSUE THREAD

**Issue by jessielyons** [vibscc/DALI#4]
Hi DALI team,

I used the example data as referenced in your publication. Cannot generate the phylogenetic tree as you have shown. I see the error as below. Can you guide what I could be doing wrong?

<img width="1210" alt="Screen Shot 2022-05-02 at 5 11 02 PM" src="https://user-images.githubusercontent.com/87676867/166345346-005717d9-dcf7-45bb-8a85-0ff64f0ad452.png">

Thanks,
Jessie

**Comment by kverstae** [comment]
Hi Jessie,

First of all, thanks for trying out DALI!
The error you described above has been fixed and you should now be able to create the phylogenetic tree again.

Kevin
